version: "3.7"

services:
  postgres:
    image: postgres:16.2
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"

  celery:
    build:
      context: ..
      dockerfile: ./infrastructure/Dockerfile
    env_file:
      - ../.env
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: "redis:6.0"
    env_file:
      - ../.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
     - REDIS_PASSWORD=${REDIS_PASSWORD}