version: "3.9"

services:
  app:
    image: karr1v/apprediska:latest
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file:
      - ../.env
    ports:
      - "${APP_PORT}:8080"

  postgres:
    image: postgres:13.3
    env_file: .env
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    env_file: .env
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  celery:
    image: karr1v/apprediska:latest
    command: celery -A app.worker.celery worker --loglevel=info
    env_file: .env
    depends_on:
      - redis

volumes:
   redis_data:
   postgres-data: