version: "3.9"

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
    env_file:
      - ../.env
    ports:
      - "5432:5432"

  celery:
    build:
      context: ..
      dockerfile: ./infrastructure/Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    env_file:
      - ../.env
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
     - "6379:6379"
    environment:
     - REDIS_PASSWORD=${REDIS_PASSWORD}
     - REDIS_PORT=6379
     - REDIS_HOST=redis
  volumes:
      - redis-vol:/var/lib/redis-vol

volumes:
  redis-vol: