version: '3.9'
services:
  backend:
    container_name: backend
    image: 15052016/cadastr_service:latest
    restart: always
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    ports:
      - 80:8080
    env_file:
      - .env

  celery:
    image: 15052016/cadastr_service:latest
    restart: always
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - backend
      - redis_db
    env_file:
      - .env

  redis_db:
    container_name: redis
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-data:/var/lib/redis
    expose:
      - "6379"

  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_DB: "lab2"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

volumes:
  redis-data: