services:
  postgres_db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgres
    env_file:
    - .env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}


  redis:
    image: redis:7
    restart: always
    volumes:
      - redis-data:/var/lib/redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery:
    image: alehanjs/lab_2:1.0
    restart: always
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - postgres_db
      - redis
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres_db
      REDIS_HOST: redis


  app:
    image: alehanjs/lab_2:1.0
    restart: always
    command: 
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    ports:
      - 80:8080
    env_file:
      - .env

volumes:
  redis-data:
  postgres-data: