services:
  postgres:
    image: postgres:15
#    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "${DB_POSTGRES_PORT}:5432"

  redis_db:
    container_name: redis
    image: redis:7-alpine
#    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery:
    container_name: celery
#    restart: always
    image: kindervunder/lab_2_vlad:latest
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis_db
      - postgres
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis

  app:
    container_name: backend
    image: kindervunder/lab_2_vlad:latest
#    restart: always
    command:
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    ports:
      - "80:8080"
    env_file:
      - .env