version: "3.7"

services:

  app:
    image: ati444/lab2:latest
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file:
      - ../.env
    ports:
      - "80:8080"

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"

  celery:
    image: ati444/lab2:latest
    command: celery -A app.worker.celery worker --loglevel=info
    env_file:
      - ../.env
    depends_on:
      - redis
      

  redis:
    image: "redis:6.0"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
     - REDIS_PASSWORD=${REDIS_PASSWORD}
     - REDIS_PORT=6379
     - REDIS_HOST=redis
  