services:
  db:
    container_name: postgres
    restart: always
    image: postgres:15
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery:
    image: mixane/lab2:1.0
    command: celery - A app.worker.celery worker --loglevel=info
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis

  app: 
    container_name: celery_program
    image: mixane/lab2:1.0
    restart: always
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file: ../.env
    depends_on:
      - redis
      - db
    ports:
      - 80:8080