# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
    restart: always
    shm_size: 128mb

  redis:
    image: redis:latest
    restart: always
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  celery:
    image: clouduppance/lab2:latest
    environment:
      DB_POSTGRES_host: postgres
      REDIS_HOST: redis
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    env_file:
      - .env
    command: celery -A app.worker.celery worker --loglevel=info

  app:
    image: clouduppance/lab2:latest
    restart: always
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis