version: "3.9"

services:
  postgres:
    image: postgres:13.3
    env_file: .env
    environment:
      POSTGRES_DB: "${DB_POSTGRES_NAME}"
      POSTGRES_USER: "${DB_POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${DB_POSTGRES_PASSWORD}"
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    env_file: .env
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: ..
      dockerfile: ./infrastructure/Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    env_file: .env
    depends_on:
      - redis

volumes:
   redis_data:
   postgres-data: