services:
  db:
    container_name: postgres
    restart: always
    image: postgres:15
    env_file:
      - ../.env
    environment:
      Postgres_DB: ${DB_POSTGRES_NAME}
      Postgres_password: ${DB_POSTGRES_PASSWORD}
      Postgres_user: ${DB_POSTGRES_USERNAME}
    
    ports:
      - "${DB_POSTGRES_PORT}:5432"

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  celery:
    build: 
      context: ..
      dockerfile: infrastructure/Dockerfile
    command: celery - A app.worker.celery worker --loglevel=info
    env_file:
      - ../.env
    environment:
      DB_POSTGRES_HOST: db
      REDIS_HOST: redis