version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:16.2
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    restart: always
    shm_size: 128mb

  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  celery:
    image: celery:latest
    environment:
      DB_POSTGRES_host: postgres
      REDIS_HOST: redis
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - redis
      - postgres
    command: celery -A app.worker.celery worker --loglevel=info