services:
  postgres:
    image: postgres:16.2-alpine
    restart: always
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
  
  redis_db:
    container_name: redis
    image: redis:7.2-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: 
      - .env
    environment: 
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery:
    container_name: celery
    restart: always
    image: nedxzer0/lab2:1.0
    command: celery -A app.worker.celery worker --loglevel=info
    build: 
      context: ..
      dockerfile: infrastructure/Dockerfile
    env_file: 
      - .env
    depends_on:
      - redis_db
      - postgres
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis
  
  app:
    container_name: app_
    image: nedxzer0/lab2:1.0
    restart: always
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    ports: 
      - 80:8080
    env_file:
      - .env