version: '3.9'
services:
  celery:
    container_name: celery
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    restart: always
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis_db
    env_file: ../.env
    environment:
      ENVIRONMENT: LOCAL
      REDIS_HOST: redis

  redis_db:
    container_name: redis
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ENVIRONMENT: PROD
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/var/lib/redis

  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_DB: "lab2"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"


volumes:
  redis-data: