version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql
    expose:
      - ${DB_POSTGRES_PORT}
  redis_db:
    container_name: redis_db
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - redis-data:/var/lib/redis
    expose:
      - ${REDIS_PORT}
  celery:
    container_name: celery
    image: useruseruser2232323/celery:latest
    restart: always
    command: celery -A app.worker.celery worker --loglevel=info
    env_file: ../.env
    depends_on:
      - redis_db
      - postgres
      - celery_program

  celery_program:
    container_name: celery_program
    image: useruseruser2232323/celery:latest
    restart: always
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file: ../.env
    depends_on:
      - redis_db
      - postgres
    ports:
      - 80:8080

volumes:
  redis-data:
  postgres-db:
