version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    
  redis_db:
    container_name: redis_db
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/var/lib/redis
  
  celery:
    container_name: celery
    restart: always
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    env_file: ../.env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      DB_POSTGRES_HOST: ${DB_POSTGRES_HOST}
    depends_on:
      - redis_db
      - postgres
volumes:  
  redis-data: