version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ENVIRONMENT: PROD

  postgres:
    container_name: postgres2
    image: postgres:16.1
    environment:
      env_file: ../.env
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "${DB_POSTGRES_PORT}:5432"
  celery:
    container_name: celery
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    env_file: ../.env
    depends_on:
      - redis
    command: celery -A app.worker.celery worker --loglevel=info
