version: "3.9"
services:

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - /path/to/postgres/data:/var/lib/postgresql/data
    ports:
      - "${DB_POSTGRESS_PORT}:5432"

  redis_db:
    container_name: redis
    restart: always
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../.env
    environment:
      - REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./redis:/var/lib/redis
    ports:
      - "${REDIS_PORT}:6379"

  celery:
    build:
      context: ..
      dockerfile: D:/web_labs/Lab-2_Infra_and_Docker/infrastructure/Dockerfile
    restart: always
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis_db
      - postgres
    env_file:
      - ../.env
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis_db
