services:
  postgre:
    container_name: postgre
    image: postgre
    env_file:
      - .env
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${DB_POSTGRES_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/database
    restart: always

  redis_db:
    container_name: redis_db
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - /redis_data:/data
    restart: always

    celery:
      container_name: celery
      build:
        context: ..
        dockerfile: infrastructure/Dockerfile
      command: celery -A app.worker.celery worker --loglevel=info
      environment:
        DB_POSTGRES_HOST: ${DB_POSTGRES_HOST}
        REDIS_HOST: ${REDIS_HOST}
      env_file: .env
      depends_on:
        - redis_db
        - postgres
      restart: always
