services:

  postgres_db:
    container_name: postgres
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}

  redis_db:
    container_name: redis  
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery:
    container_name: celery
    restart: always
    image: marsi/lab
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis_db
      - postgres_db
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres_db
      REDIS_HOST: redis_db

  app:
    container_name: application
    image: marsi/lab
    restart: always
    command:
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    ports:
      - 8002:8080
    env_file:
      - .env