services:
  db:
    container_name: postgres
    restart: always
    image: postgres:15
    env_file:
      - .env
    environment:
      Postgres_DB: ${DB_POSTGRES_NAME}
      Postgres_password: ${DB_POSTGRES_PASSWORD}
      Postgres_user: ${DB_POSTGRES_USERNAME}

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery:
    image: tr3n1k/lab_2:latest
    command: celery - A app.worker.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: db
      REDIS_HOST: redis
  
  app: 