version: '3.9'

services:
  app:
    container_name: app2
    image: mtsygikalo/someapp
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file: ../.env
    ports:
      - ${MAIN_PORT}:8080

  celery:
    container_name: celery
    image: mtsygikalo/someapp
    env_file: ../.env
    depends_on:
      - app
      - redis
    command: celery -A app.worker.celery worker --loglevel=info

  redis:
    container_name: redis
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      ENVIRONMENT: PROD

  postgres:
    container_name: postgres2
    image: postgres:16.1
    environment:
      env_file: ../.env
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}

