services:
  postgres:
    image: postgres:16.2-alpine
    restart: always
    env_file: 
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - "${DB_POSTGRES_PORT}:5432"
  
  redis_db:
    container_name: redis
    image: redis:7.2-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../.env
    environment: 
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  celery:
    container_name: celery
    build: 
      context: ..
      dockerfile: infrastructure/Dockerfile
    restart: always
    env_file:
      - ../.env
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis_db
      - postgres
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis_db