
FROM python:3.9-slim

RUN curl -sSL https://install.python-poetry.org | python3 -
COPY pyproject.toml poetry.lock /app/
WORKDIR /app
RUN poetry config virtualenvs.in-project true \
    && poetry install --no-dev
COPY app /app/app
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"]
