services:
  postgres_db:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgres
    env_file:
    - .env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - "${DB_POSTGRES_PORT}:5432"


  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/var/lib/redis
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports: 
      - "${REDIS_PORT}:6379"

  celery:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - postgres_db
      - redis
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres_db
      REDIS_HOST: redis

volumes:
  redis-data:
  postgres-data:
