services:
  postgres_db:
    image: postgres:16.2
    restart: always
    env_file: ../.env
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USERNAME: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    
  
  redis_db:
    container_name: redis
    image: redis:7-alpine
    restart: always
    env_file: ../.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  celery:
    container_name: celery
    restart: always
    env_file: ../.env
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    depends_on:
      - redis_db
      - postgres_db
    command: celery -A app.worker.celery worker --loglevel=info
    environment:
      DB_POSTGRES_HOST: postgres_db
      REDIS_HOST: redis_db
