version: "3.9"

services:
  redis:
    image: redis:latest
    env_file: ../.env
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379

  postgres:
    container_name: postgres
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    env_file: ../.env
