services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgres

  redis_db:
    container_name: redis
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis-data:/var/lib/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  celery:
    container_name: celery
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    restart: always
    command: celery -A app.worker.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis_db
    depends_on:
      - redis_db
      - postgres

volumes:
  redis-data:
  postgres-data: