version: "3.9"

services:
  redis:
    image: redis:latest
    env_file: .env
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379
    volumes:
      - redis_data:/data

  postgres:
    container_name: postgres
    image: postgres:16.2
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    env_file: .env

volumes:
  redis_data:
  postgres-data: