services:
  postgres:
    image: postgres: 16.2
    restart: always 
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRESS_PASSWORD}
      user: ${DB_POSTGRES_USERNAME}
      DB: ${DB_POSTGRES_NAME}
    ports:
      - "${DB_POSTGRES_PORT}:5432"

  redis:
    container_name: redis
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

  celery:
    container_name: celery
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    restart: always
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis_db
      - postgres
    env_file:
      - ../.env
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis_db