services:
  postgres:
    restart: always
    image: postgres:16.2
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}


  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
        -../.env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}


  celery:
    container_name: celery
    restart: always
    image: aleksandrsemyshin/lab_2:1.0
    command: celery -A app.worker.celery worker --loglevel=info
    env_file:
      - ../.env
    depends_on:
      - redis_db
      - postgres


  app:
    restart: always
    image: aleksandrsemyshin/lab_2:1.0
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file:
      - ../.env
    depends_on:
      - redis_db
      - postgres
    ports:
      - 80:8080

