services:

  postgres:
    image: postgres: 15
    restart: always 
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRESS_PASSWORD}
      user: ${DB_POSTGRES_USERNAME}
      DB: ${DB_POSTGRES_NAME}


  redis:
    image: redis:7
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      -  .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}


  celery:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    image:
    restart: always
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis_db
      - postgres
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis

  app:
    container_name: backend
    image: 
    restart: always
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    env_file:
      - .env
    depends_on:
      postgres
      redis
    ports:
      - "80:8080"
    env_file:
      - .env