services:
  postgres:
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - /path/to/postgres/data:/var/lib/postgresql/data

  redis_db:
    container_name: redis
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - /path/to/redis/data:/data

  celery:
    container_name: celery
    restart: always
    image: inactivelele/laba2:latest
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis_db
      - postgres
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis

  app:
    container_name: backend
    image: inactivelele/laba2:latest
    restart: always
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    ports:
      - 80:8080
    env_file:
      - .env
