services:
  app:
    container_name: app
    image: egork8/asb36-kruchinin:infra
    depends_on:
      - postgres_db
      - redis_db
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080 --workers 4"
    volumes:
      - ./app:/src/app
    ports:
      - 80:8080
    env_file:
      - .env
    restart: always

  celery:
    container_name: celery
    image: egork8/asb36-kruchinin:infra
    depends_on:
      - redis_db
      - postgres_db
      - app
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./app:/src/celery
    env_file:
      - .env
    environment:
      DB_POSTGRES_HOST: postgres
      REDIS_HOST: redis
    restart: always
    

  redis_db:
    container_name: redis_db
    image: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - /redis_data:/data
    restart: always

  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    volumes:
      - .postgres:/var/lib/postgres/database
    restart: always

